config/routes.rb
Punch::Application.routes.draw do
  resources :employees, only: [:index, :create, :destroy]

  resources :clocks, only: [:new, :create]
  get 'report', to: 'clocks#report'

  root to: 'clocks#new'
end

app/models/clock_record.rb
class ClockRecord < ActiveRecord::Base
  attr_accessible :employee_id, :clocked_in
  validates_presence_of :employee_id
  belongs_to :employee

  def clocked_in?
    clocked_in
  end

end

app/models/employee.rb
class Employee < ActiveRecord::Base
  attr_accessible :employee_card_id, :first_name, :last_name, :is_admin
  validates_presence_of :employee_card_id, :first_name, :last_name
  has_many :clock_records

  # Remeber:
  # When you write using ActiveRecord it gets localtime, converts and saves it in UTC time
  # When you search it gets localtime, converts and uses it in UTC
  # When you read it retuns UTC time
  # Time.now returns localtime
  # 1.days.ago and similar return UTC time
  # All calculations here should be made in localtime

  def seven_days_records
    clock_records.where("created_at >= ?", 7.days.ago.localtime.beginning_of_day).order('created_at')
  end

  def today_hours
    work_hours(Time.now.beginning_of_day)
  end

  def seven_days_hours
    work_hours(7.days.ago.localtime.beginning_of_day)
  end

  def is_admin?
    is_admin
  end

  def last_work_hours
    last_out = clock_records.where(clocked_in: false).last.created_at
    last_work_seconds = last_out.to_i - clock_records.where('created_at <= ?', last_out).where(clocked_in: true).last.created_at.to_i rescue 0

    mm, ss = last_work_seconds.divmod(60)
    hh, mm = mm.divmod(60)

    "%02d:%02d:%02d" % [hh, mm, ss]
  rescue => e
    Rails.logger.error "Error happened in last_work_hours:\n\t#{e.inspect}"
    "N/A"
  end

  private

  def work_hours(start)
    total = 0
    last_clock_records = clock_records.where("created_at >= ?", start).order('created_at')

    total = last_clock_records.first.created_at.localtime.to_i - start.to_i unless last_clock_records.first.clocked_in
    last_clock_records.each_with_index do |cr, i|
      next unless cr.clocked_in

      next_clock_out = last_clock_records[i+1].created_at.localtime rescue Time.now
      diff = next_clock_out - cr.created_at.localtime
      total += diff
    end

    mm, ss = total.divmod(60)
    hh, mm = mm.divmod(60)

    "%02d:%02d:%02d" % [hh, mm, ss]
  rescue => e
    Rails.logger.error "Error happened in work_hours:\n\t#{e.inspect}"
    "N/A"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/clocks_controller.rb
class ClocksController < ApplicationController

  def new
    @clock_record = ClockRecord.new
  end

  def create
    if params[:report]
      redirect_to action: "report", employeeId: params[:employeeId]
      return
    end

    @employee = Employee.find_by_employee_card_id(params[:employeeId])
    clocked_in = @employee.clock_records.last.clocked_in rescue false
    @clock_record = ClockRecord.create!(
      employee_id: @employee.id,
      clocked_in: !clocked_in
    )

    @all_other_employees = Employee.where("id != ?", @employee.id) if @employee.is_admin?

    render "today_hours"
  rescue => e
    Rails.logger.error "Error happened during Clocking In/Out:\n\t#{e.inspect}"
    flash[:alert] = "Error happend trying to clock you in/out. Please check your Employee Card ID or talk to support."
    redirect_to action: "new"
  end

  def report
    Rails.logger.debug "report params: #{params.inspect}"
    @employee = Employee.find_by_employee_card_id(params[:employeeId])
    fail "Employee not found" unless @employee
  rescue => e
    Rails.logger.error "Error happened during creating report:\n\t#{e.inspect}"
    flash[:alert] = "Employee not found. Please check your Employee Card ID or talk to support."
    redirect_to action: "new"
  end

end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController

  def index
    @all_employees = Employee.all
    @employee = Employee.new
  end

  def create
    Employee.create!(
      employee_card_id: params[:employeeCardId],
      first_name: params[:firstName],
      last_name: params[:lastName],
      is_admin: params[:isAdmin]
    )
  rescue => e
    Rails.logger.error "Error happened during employee creation:\n\t#{e.inspect}"
    flash[:alert] = "Error happened during employee creation"
  ensure
    redirect_to action: "index"
  end

  def destroy
    Rails.logger.debug "Destroyed!"
    @employee = Employee.find(params[:id])
    @employee.destroy
    render json: {message: "#{@employee.first_name} #{@employee.last_name} was successfully removed"}
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/clocks/_all_employees_hours.html.erb
<% if @employee.is_admin? %>

  <table class="punch-table">
    <thead>
      <tr><th>Employee ID</th><th>First Name</th><th>Last Name</th><th>Last 7 days</th><th>Current State</th><th>Last change</th></tr>
    </thead>
    <tbody>
      <% @all_other_employees.each do |e| %>
        <% last_clock_record = e.clock_records.last %>
        <tr>
          <td><%= e.employee_card_id %></td>
          <td><%= e.first_name %></td>
          <td><%= e.last_name %></td>
          <td><%= e.seven_days_hours %></td>
          <% if last_clock_record %>
            <td><%= last_clock_record.clocked_in ? 'In' : 'Out' %></td>
            <td><%= last_clock_record.created_at.localtime.strftime('%c') %></td>
          <% else %>
            <td>N/A</td>
            <td>N/A</td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

<% end %>

app/views/clocks/_clock_form.html.erb
<%= form_for @clock_record, url: {action: "create"}, html: {class: "punch-border", id: 'clockForm'} do |f| %>
    <label for="employeeId" class="punch-label">Emploee ID</label>
    <input name="employeeId" id="employeeId" placeholder="Emploee ID" class="punch-text-input" required/>
    <div class="punch-button-area">
        <button type="submit" name="submitInOut" value="submitInOut" class="punch-button">Clock In/Out</button>
        <button type="submit" name="report" value="report" class="punch-button">Report</button>
    </div>
<% end %>

app/views/clocks/new.html.erb
<div class="punch-border" id="clockArea">
  <p class="punch-text">Enter ID from your Emploee Card and press 'Clock In/Out' to clock in or out. Press 'Report' button if you just want to see your work hours without clocking in/out.<br/><br/>If you forget to clock in/out it leads to too many work hours in report. It will look suspicios for your manager.<p>

  <%= render 'clock_form' %>

  <% if flash[:alert] %>
    <p class="punch-error"><%= flash[:alert] %></p>
  <% end %>
</div>

app/views/clocks/report.html.erb
<div class="punch-border" id="reportArea">
  <p class="punch-text">Hi, <%= @employee.first_name %> <%= @employee.last_name %>. During last 7 days you worked: <%= @employee.seven_days_hours %>.</p>
</div>

<table class="punch-table">
  <thead>
    <tr><th>Action</th><th>When</th></tr>
  </thead>
  <tbody>
    <% @employee.seven_days_records.each do |r| %>
      <tr>
        <td><%= r.clocked_in ? 'In' : 'Out' %></td>
        <td><%= r.created_at.localtime.strftime('%c') %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/clocks/today_hours.html.erb
<div class="punch-border" id="clockArea">
  <p class="punch-text"><%= @clock_record.clocked_in ? 'Hi' : 'Bye' %>, <%= @employee.first_name %> <%= @employee.last_name %>. You'successfully <b>clocked <%= @clock_record.clocked_in ? 'in' : 'out' %></b>. Last time you worked: <%= @employee.last_work_hours %> Today you worked: <%= @employee.today_hours %>. Now is <%= Time.now.strftime('%c') %>.</p>
</div>

<%= render 'all_employees_hours' %>

app/views/employees/_employee_form.html.erb
<%= form_for @employee, url: {action: "create"}, html: {class: "punch-border", id: 'employeeForm'} do |f| %>
    <label for="employeeCardId" class="punch-label">Emploee Card ID</label>
    <input id="employeeCardId" name="employeeCardId" placeholder="Employee Card ID" class="punch-text-input" required/>
    
    <label for="firstName" class="punch-label">First Name</label>
    <input id="firstName" name="firstName" placeholder="First Name" class="punch-text-input" required/>
    
    <label for="lastName" class="punch-label">Last Name</label>
    <input id="lastName" name="lastName" placeholder="Last Name" class="punch-text-input" required/>
    
    <label for="isAdmin" class="punch-label">Adminstrator?</label>
    <input type="checkbox" id="isAdmin" name="isAdmin" class="punch-checkbox"/>

    <div class="punch-button-area">
        <button type="submit" id="createEmployeeCard" class="punch-button">Create Employee Card</button>
    </div>

    <% if flash[:alert] %>
       <p class="punch-error"><%= flash[:alert] %></p>
    <% end %>

<% end %>

app/views/employees/_employee_table.html.erb
<table class="punch-table">
  <thead>
    <tr><th>Employee ID</th><th>First Name</th><th>Last Name</th><th>Admin?</th><th>Delete</th></tr>
  </thead>
  <tbody>
    <% @all_employees.each do |e| %>
      <tr>
        <td><%= e.employee_card_id %></td>
        <td><%= e.first_name %></td>
        <td><%= e.last_name %></td>
        <td><%= e.is_admin ? 'yes' : 'no' %></td>
        <td><%= image_tag "trashcan.png", class: 'destroyEmployee', employee_id: e.id %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/employees/index.html.erb
<%= render 'employee_form' %>
<%= render 'employee_table' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Punch</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<ul class="punch-nav-menu">
    <li><a href="/">Punch Clock</a></li>
    <li><%= link_to 'Employees', employees_path %></li>
</ul>

<%= yield %>

</body>
</html>